"""
Jobs API router - Handles all job-related endpoints.
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, field_validator
from typing import Optional, Dict, Any

from src.services.crew_runner import CrewRunner, ResumeCrew
from src.core.models.schemas import (
    JobSearchRequest,
    JobSearchResponse,
    MatchRequest,
    MatchResponse,
    TailorRequest,
    TailorResponse,
    ApplyRequest,
    ApplyResponse,
    JobAnalysis,
    CompanyResearch,
    TailorResult,
    GeneratedResume,
    WorkflowReport
)
from src.core.utils.pdf import extract_text_from_pdf_bytes

router = APIRouter(prefix="/jobs", tags=["Jobs"])

# Initialize crew runner (shared instance)
crew_runner = CrewRunner()


@router.post("/search", response_model=JobSearchResponse)
async def search_jobs(request: JobSearchRequest):
    """
    Search for job opportunities using the job scout agent.
    
    This endpoint uses the CrewAI job scout agent to discover job opportunities
    based on the provided search criteria.
    """
    try:
        jobs = crew_runner.run_job_scout(
            search_criteria=request.criteria,
            config=request.config
        )
        return JobSearchResponse(
            jobs=jobs,
            total=len(jobs),
            message=f"Found {len(jobs)} job opportunities"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Job search failed: {str(e)}")


@router.post("/match", response_model=MatchResponse)
async def match_jobs(request: MatchRequest):
    """
    This endpoint uses the matcher agent to analyze job descriptions and
    match them with the provided resume context using RAG techniques.
    """
    try:
        matches = crew_runner.run_matcher(
            job_postings=request.job_postings,
            resume_context=request.resume_context,
            config=request.config
        )
        
        return MatchResponse(
            matches=matches,
            total_matched=len(matches),
            message=f"Matched {len(matches)} jobs"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Job matching failed: {str(e)}")


@router.post("/tailor", response_model=TailorResponse)
async def tailor_documents(request: TailorRequest):
    """
    Generate tailored resume and cover letter for a specific job.
    
    This endpoint uses the tailor agent to create customized documents
    optimized for the specified job posting.
    """
    try:
        tailored_docs = crew_runner.run_tailor(
            job_posting=request.job_posting,
            base_resume=request.base_resume,
            config=request.config
        )
        
        job_id = request.job_posting.id or "unknown"
        
        return TailorResponse(
            job_id=job_id,
            resume=tailored_docs.get("resume", ""),
            cover_letter=tailored_docs.get("cover_letter", ""),
            format="markdown",
            message="Documents tailored successfully"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Document tailoring failed: {str(e)}")


@router.post("/apply", response_model=ApplyResponse)
async def apply_to_job(request: ApplyRequest):
    """
    Submit a job application using the applicator agent.
    
    This endpoint uses the applicator agent to submit job applications.
    By default, applications require manual review unless auto-submit is enabled.
    """
    try:
        result = crew_runner.run_applicator(
            job_posting=request.job_posting,
            tailored_resume=request.tailored_resume,
            cover_letter=request.cover_letter,
            config=request.config
        )
        
        job_id = request.job_posting.id or "unknown"
        
        return ApplyResponse(
            application_id=None,  # Would be generated by storage layer
            status=result.get("status", "pending"),
            message=result.get("message", "Application processed"),
            job_id=job_id,
            submitted_at=None  # Would be set if actually submitted
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Application submission failed: {str(e)}")


# New workflow agents endpoints

class JobAnalyzerRequest(BaseModel):
    """Request for job analyzer."""
    job_description: str
    job_url: Optional[str] = None


@router.post("/analyze", response_model=JobAnalysis)
async def analyze_job(request: JobAnalyzerRequest):
    """
    Analyze a job description and extract structured information.

    The job_description should be the full text of the job posting.
    This is typically obtained from the job_scout agent output.
    """
    try:
        analysis = crew_runner.run_job_analyzer(
            job_description=request.job_description,
            job_url=request.job_url
        )
        return analysis
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Job analysis failed: {str(e)}")


class CompanyResearchRequest(BaseModel):
    """Request for company research."""
    company_name: str


@router.post("/research-company", response_model=CompanyResearch)
async def research_company(request: CompanyResearchRequest):
    """
    Research a company and gather information about culture, size, and interview tips.
    """
    try:
        research = crew_runner.run_company_research(request.company_name)
        return research
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Company research failed: {str(e)}")


class TailorOptimizeRequest(BaseModel):
    """Request for resume tailoring."""
    base_resume: str
    job_analysis: dict  # JobAnalysis as dict

    @field_validator("base_resume", mode="before")
    @classmethod
    def _normalize_base_resume(cls, v: str) -> str:
        """Allow base_resume to be sent as base64-encoded PDF and auto-extract text."""
        if isinstance(v, str):
            return extract_text_from_pdf_if_base64(v)
        return v


@router.post("/tailor-optimize", response_model=TailorResult)
async def tailor_optimize(request: TailorOptimizeRequest):
    """
    Tailor and optimize a resume for a specific job.
    """
    try:
        # Convert dict back to JobAnalysis if needed
        tailor = crew_runner.run_tailor_optimize(request.base_resume, JobAnalysis(**request.job_analysis))
        return tailor
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Resume tailoring failed: {str(e)}")


class GenerateResumeRequest(BaseModel):
    """Request for resume generation."""
    optimized_content: dict
    output_format: str = "markdown"


@router.post("/generate-resume", response_model=GeneratedResume)
async def generate_resume(request: GenerateResumeRequest):
    """
    Generate a formatted resume from optimized content.
    """
    try:
        resume = crew_runner.run_generate_resume(request.optimized_content, request.output_format)
        return resume
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Resume generation failed: {str(e)}")


class FullWorkflowRequest(BaseModel):
    """Request for full workflow execution."""
    job_url: str
    base_resume: str
    options: dict = {}


@router.post("/process", response_model=WorkflowReport)
async def process_job(request: FullWorkflowRequest):
    """
    Run the complete workflow: analyze job -> research company -> tailor resume -> generate -> report.

    Takes a job URL and base resume, and returns a comprehensive report with generated resume.
    """
    try:
        report = crew_runner.run_full_workflow(request.job_url, request.base_resume, request.options)
        return report
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Workflow execution failed: {str(e)}")


class ResumeCrewRequest(BaseModel):
    """Request for ResumeCrew workflow execution."""
    job_input: str
    base_resume: str
    company_name: Optional[str] = None

    @field_validator("base_resume", mode="before")
    @classmethod
    def _normalize_base_resume(cls, v: str) -> str:
        """Allow base_resume to be sent as base64-encoded PDF and auto-extract text."""
        if isinstance(v, str):
            return extract_text_from_pdf_if_base64(v)
        return v


class ResumeCrewResponse(BaseModel):
    """Response from ResumeCrew workflow execution."""
    job_analysis: Dict[str, Any]
    company_research: Dict[str, Any]
    tailor_recommendations: Dict[str, Any]
    generated_resume: Dict[str, Any]
    workflow_report: Dict[str, Any]


@router.post("/resume-crew", response_model=ResumeCrewResponse)
async def run_resume_crew(request: ResumeCrewRequest):
    """
    Run the ResumeCrew workflow with YAML-configured agents.

    This endpoint uses the ResumeCrew class which loads all agent and task
    configurations from YAML files, providing a centralized and maintainable
    way to manage prompts.

    The workflow uses the @crew decorator pattern from CrewAI, which automatically
    orchestrates all agents and tasks in the proper sequence.

    Args:
        job_input: Job URL or job posting text
        base_resume: Your base resume content
        company_name: Optional company name (extracted from job if not provided)

    Returns:
        Complete workflow results including:
        - Job analysis
        - Company research
        - Resume tailoring recommendations
        - Generated optimized resume
        - Comprehensive workflow report
    """
    try:
        # Create ResumeCrew instance with input data
        resume_crew_instance = ResumeCrew(
            job_input=request.job_input,
            base_resume=request.base_resume,
            company_name=request.company_name
        )
        
        result = resume_crew_instance.crew().kickoff()

        # Parse the result
        import json
        import re

        try:
            parsed_result = json.loads(str(result))
        except json.JSONDecodeError:
            
            json_match = re.search(r'\{.*\}', str(result), re.DOTALL)
            if json_match:
                parsed_result = json.loads(json_match.group())
            else:
                
                parsed_result = {
                    "job_analysis": {},
                    "company_research": {},
                    "tailor_recommendations": {},
                    "generated_resume": {"content": str(result)},
                    "workflow_report": {"summary": str(result)}
                }

        # Ensure all required fields are present
        response_data = {
            "job_analysis": parsed_result.get("job_analysis", {}),
            "company_research": parsed_result.get("company_research", {}),
            "tailor_recommendations": parsed_result.get("tailor_recommendations", {}),
            "generated_resume": parsed_result.get("generated_resume", {}),
            "workflow_report": parsed_result.get("workflow_report", {})
        }

        return ResumeCrewResponse(**response_data)
    except Exception as e:
        import traceback
        error_detail = f"ResumeCrew workflow failed: {str(e)}\n{traceback.format_exc()}"
        raise HTTPException(status_code=500, detail=error_detail)

